/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPVMEngine,
  IPVMEngineInterface,
} from "../../../contracts/interfaces/IPVMEngine";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "input",
        type: "bytes",
      },
    ],
    name: "optimizeAllocation",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "input",
        type: "bytes",
      },
    ],
    name: "rebalanceBasket",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPVMEngine__factory {
  static readonly abi = _abi;
  static createInterface(): IPVMEngineInterface {
    return new Interface(_abi) as IPVMEngineInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPVMEngine {
    return new Contract(address, _abi, runner) as unknown as IPVMEngine;
  }
}
