/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IXCMPrecompile,
  IXCMPrecompileInterface,
} from "../../../contracts/interfaces/IXCMPrecompile";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "destParaId",
        type: "uint32",
      },
      {
        internalType: "bytes",
        name: "xcmMessage",
        type: "bytes",
      },
    ],
    name: "sendXCM",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "destParaId",
        type: "uint32",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "beneficiary",
        type: "address",
      },
    ],
    name: "teleportAsset",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IXCMPrecompile__factory {
  static readonly abi = _abi;
  static createInterface(): IXCMPrecompileInterface {
    return new Interface(_abi) as IXCMPrecompileInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IXCMPrecompile {
    return new Contract(address, _abi, runner) as unknown as IXCMPrecompile;
  }
}
