/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BasketManager {
  export type AllocationConfigStruct = {
    paraId: BigNumberish;
    protocol: AddressLike;
    weightBps: BigNumberish;
    depositCall: BytesLike;
    withdrawCall: BytesLike;
  };

  export type AllocationConfigStructOutput = [
    paraId: bigint,
    protocol: string,
    weightBps: bigint,
    depositCall: string,
    withdrawCall: string
  ] & {
    paraId: bigint;
    protocol: string;
    weightBps: bigint;
    depositCall: string;
    withdrawCall: string;
  };

  export type BasketStruct = {
    id: BigNumberish;
    name: string;
    token: AddressLike;
    allocations: BasketManager.AllocationConfigStruct[];
    totalDeposited: BigNumberish;
    active: boolean;
  };

  export type BasketStructOutput = [
    id: bigint,
    name: string,
    token: string,
    allocations: BasketManager.AllocationConfigStructOutput[],
    totalDeposited: bigint,
    active: boolean
  ] & {
    id: bigint;
    name: string;
    token: string;
    allocations: BasketManager.AllocationConfigStructOutput[];
    totalDeposited: bigint;
    active: boolean;
  };
}

export interface BasketManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PVM_ENGINE"
      | "XCM_PRECOMPILE"
      | "baskets"
      | "createBasket"
      | "deposit"
      | "getBasket"
      | "getBasketNAV"
      | "nextBasketId"
      | "owner"
      | "rebalance"
      | "rebalanceThresholdBps"
      | "userPositions"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BasketCreated"
      | "DeploymentDispatched"
      | "Deposited"
      | "Rebalanced"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "PVM_ENGINE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "XCM_PRECOMPILE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "baskets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBasket",
    values: [string, string, BasketManager.AllocationConfigStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBasket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBasketNAV",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextBasketId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rebalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rebalanceThresholdBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userPositions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "PVM_ENGINE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "XCM_PRECOMPILE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "baskets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createBasket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBasket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBasketNAV",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextBasketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rebalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rebalanceThresholdBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace BasketCreatedEvent {
  export type InputTuple = [
    basketId: BigNumberish,
    name: string,
    token: AddressLike
  ];
  export type OutputTuple = [basketId: bigint, name: string, token: string];
  export interface OutputObject {
    basketId: bigint;
    name: string;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeploymentDispatchedEvent {
  export type InputTuple = [
    basketId: BigNumberish,
    paraId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [basketId: bigint, paraId: bigint, amount: bigint];
  export interface OutputObject {
    basketId: bigint;
    paraId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    basketId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish,
    tokensMinted: BigNumberish
  ];
  export type OutputTuple = [
    basketId: bigint,
    user: string,
    amount: bigint,
    tokensMinted: bigint
  ];
  export interface OutputObject {
    basketId: bigint;
    user: string;
    amount: bigint;
    tokensMinted: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RebalancedEvent {
  export type InputTuple = [basketId: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [basketId: bigint, timestamp: bigint];
  export interface OutputObject {
    basketId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    basketId: BigNumberish,
    user: AddressLike,
    tokensBurned: BigNumberish,
    amountOut: BigNumberish
  ];
  export type OutputTuple = [
    basketId: bigint,
    user: string,
    tokensBurned: bigint,
    amountOut: bigint
  ];
  export interface OutputObject {
    basketId: bigint;
    user: string;
    tokensBurned: bigint;
    amountOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BasketManager extends BaseContract {
  connect(runner?: ContractRunner | null): BasketManager;
  waitForDeployment(): Promise<this>;

  interface: BasketManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PVM_ENGINE: TypedContractMethod<[], [string], "view">;

  XCM_PRECOMPILE: TypedContractMethod<[], [string], "view">;

  baskets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, boolean] & {
        id: bigint;
        name: string;
        token: string;
        totalDeposited: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  createBasket: TypedContractMethod<
    [
      name: string,
      symbol: string,
      allocations: BasketManager.AllocationConfigStruct[]
    ],
    [bigint],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[basketId: BigNumberish], [bigint], "payable">;

  getBasket: TypedContractMethod<
    [basketId: BigNumberish],
    [BasketManager.BasketStructOutput],
    "view"
  >;

  getBasketNAV: TypedContractMethod<[basketId: BigNumberish], [bigint], "view">;

  nextBasketId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  rebalance: TypedContractMethod<
    [basketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  rebalanceThresholdBps: TypedContractMethod<[], [bigint], "view">;

  userPositions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        basketId: bigint;
        tokenBalance: bigint;
        depositedAt: bigint;
      }
    ],
    "view"
  >;

  withdraw: TypedContractMethod<
    [basketId: BigNumberish, tokenAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PVM_ENGINE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "XCM_PRECOMPILE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "baskets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, boolean] & {
        id: bigint;
        name: string;
        token: string;
        totalDeposited: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createBasket"
  ): TypedContractMethod<
    [
      name: string,
      symbol: string,
      allocations: BasketManager.AllocationConfigStruct[]
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[basketId: BigNumberish], [bigint], "payable">;
  getFunction(
    nameOrSignature: "getBasket"
  ): TypedContractMethod<
    [basketId: BigNumberish],
    [BasketManager.BasketStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBasketNAV"
  ): TypedContractMethod<[basketId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextBasketId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rebalance"
  ): TypedContractMethod<[basketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rebalanceThresholdBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "userPositions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        basketId: bigint;
        tokenBalance: bigint;
        depositedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [basketId: BigNumberish, tokenAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BasketCreated"
  ): TypedContractEvent<
    BasketCreatedEvent.InputTuple,
    BasketCreatedEvent.OutputTuple,
    BasketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DeploymentDispatched"
  ): TypedContractEvent<
    DeploymentDispatchedEvent.InputTuple,
    DeploymentDispatchedEvent.OutputTuple,
    DeploymentDispatchedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "Rebalanced"
  ): TypedContractEvent<
    RebalancedEvent.InputTuple,
    RebalancedEvent.OutputTuple,
    RebalancedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "BasketCreated(uint256,string,address)": TypedContractEvent<
      BasketCreatedEvent.InputTuple,
      BasketCreatedEvent.OutputTuple,
      BasketCreatedEvent.OutputObject
    >;
    BasketCreated: TypedContractEvent<
      BasketCreatedEvent.InputTuple,
      BasketCreatedEvent.OutputTuple,
      BasketCreatedEvent.OutputObject
    >;

    "DeploymentDispatched(uint256,uint32,uint256)": TypedContractEvent<
      DeploymentDispatchedEvent.InputTuple,
      DeploymentDispatchedEvent.OutputTuple,
      DeploymentDispatchedEvent.OutputObject
    >;
    DeploymentDispatched: TypedContractEvent<
      DeploymentDispatchedEvent.InputTuple,
      DeploymentDispatchedEvent.OutputTuple,
      DeploymentDispatchedEvent.OutputObject
    >;

    "Deposited(uint256,address,uint256,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "Rebalanced(uint256,uint256)": TypedContractEvent<
      RebalancedEvent.InputTuple,
      RebalancedEvent.OutputTuple,
      RebalancedEvent.OutputObject
    >;
    Rebalanced: TypedContractEvent<
      RebalancedEvent.InputTuple,
      RebalancedEvent.OutputTuple,
      RebalancedEvent.OutputObject
    >;

    "Withdrawn(uint256,address,uint256,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
