/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockPVMEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_WEIGHT_BPS"
      | "MIN_WEIGHT_BPS"
      | "optimizeAllocation"
      | "rebalanceBasket"
      | "riskAdjustedYield"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "MAX_WEIGHT_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_WEIGHT_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "optimizeAllocation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rebalanceBasket",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "riskAdjustedYield",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_WEIGHT_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_WEIGHT_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "optimizeAllocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rebalanceBasket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "riskAdjustedYield",
    data: BytesLike
  ): Result;
}

export interface MockPVMEngine extends BaseContract {
  connect(runner?: ContractRunner | null): MockPVMEngine;
  waitForDeployment(): Promise<this>;

  interface: MockPVMEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_WEIGHT_BPS: TypedContractMethod<[], [bigint], "view">;

  MIN_WEIGHT_BPS: TypedContractMethod<[], [bigint], "view">;

  optimizeAllocation: TypedContractMethod<[input: BytesLike], [string], "view">;

  rebalanceBasket: TypedContractMethod<[input: BytesLike], [string], "view">;

  riskAdjustedYield: TypedContractMethod<[input: BytesLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_WEIGHT_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_WEIGHT_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "optimizeAllocation"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "rebalanceBasket"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "riskAdjustedYield"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;

  filters: {};
}
